### PR TITLE
add list weighting for diversity

### PR DESCRIPTION
**Pull request by latazzajones**
Women and people of color are weighted higher to increase the chance that they show up on the home page. The purpose is to ensure that everyone feels welcome.

### CODE REVIEW

**Comment by jgaskins** [comment]
`E_TOOMANYWHITEGUYS`

**Comment by nerdEd** [comment]
:shipit: y'all are both collaborators on GH and Heroku

**Comment by jjulian** [comment]
I haven't merged to master or deployed simply because I don't feel strongly
about this PR. As Ed says, you both have permissions, so merge away!

**Comment by BSierakowski** [comment]
:+1:

**Comment by latazzajones** [comment]
@BSierakowski Thanks! I'm gunna make some small edits to this next week then merge it.

**Comment by BSierakowski** [comment]
Saw the new member PR which brought me back to this branch, is this something we still want to launch? If so, the readme will need to be updated for people adding themselves, which makes me wonder if there should be a different interface to make it easier for new members to classify themselves as they want. 

Which also makes me think: is it OK to have member values like "woman" and "person of color"? Does that sort of singling out have the opposite effect that the PR is looking to achieve (being more welcoming to a diverse community)? Does that send a message like "everyone is welcome! Now tell us exactly how you're different."

The other implementation is to move the "0.3 if you're a white guy, otherwise 0.9" comment to the readme section and keep everything else the same.

**Comment by latazzajones** [comment]
@BSierakowski I think it's a little tricky - my original goal was to make sure that the landing page reflected our diversity even though there's a lot of people in the yaml file from when the meetup was less diverse. BUT!! We just continue increasing in diversity and I don't think this work is needed any more ... despite it being an interesting idea. I'm gunna close this pr.

**Comment by jgaskins** [comment]
I noticed last night while working with Alice that the page is significantly more diverse even without this PR, which is great, but it could still get better. I still think the list weighting is a good idea, but maybe a 3:1 ratio isn't what we need anymore.

Might not be a bad idea to prune some of the members who don't attend anymore, nearly all of whom are white dudes. :-) That might help a bit, as well.

**Comment by solipet** [comment]
Aside from the issue of maintenance, we could add last_attended and estimate that last time someone showed up and weight it to the more regular attendees — that way it would more likely reflect the actual diversity (or lack thereof) at any given point.

Again, maintenance may be annoying and fraught with errors.  ;-)

-Doug

**Pull request closed without merging**
