### PR TITLE
Added my photo!!

### PR DESCRIPTION
**Pull request by a-jean**

### CODE REVIEW

**Comment by latazzajones** [comment]
Hey Ashlely, 
If you have a sec - could you fix the conflicts in your branch? I think you branched off an old version of master since Doug was merging stuff in at the same time. 

Tash

**Comment by solipet** [comment]
Also, in the members.yml file, you need a line with just a dash above the section with your deets.  That's a yml syntax thing indicating a sequence (i.e., array) of things.  See http://yaml.org/YAML_for_ruby.html#mixed_mapping for a more complete explanation.

**Comment by solipet** [comment]
One final nit-pick -- can you rename your image file to identify it as yours?  e.g., `git mv image2.jpeg ashley-jean.jpeg` or similar.

**Comment by a-jean** [comment]
Hi -
made a new pull request, please see changes!

**Comment by latazzajones** [comment]
this has moved to pr #36

**Pull request closed without merging**
